<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Password</name>
   <tag></tag>
   <elementGuidId>c477c025-77a6-4bc7-84c1-0921d939bb09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Input Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2306ea04-7b0d-4d02-8ead-cb956de9e8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8b8976db-65e8-4059-8833-05b40d1bd596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>560af27f-4ace-492c-85ef-8427d3468de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Password</value>
      <webElementGuid>20202025-f610-45fa-a426-090ec6b51e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 h-[52px] flex items-center  border border-[#DEDEDE] placeholder:text-[#DEDEDE] rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 text-black bg-white </value>
      <webElementGuid>19c2d9a5-5fb0-4c9a-ad95-b28d0f1f04a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>06400fa5-ad64-4090-b353-ce960b1f8579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;flex justify-end md:justify-end items-center bg-cover bg-center global-bg&quot;]/div[@class=&quot;rounded-lg&quot;]/div[@class=&quot;bg-white p-10 rounded-lg w-[528px] mx-[73px] my-8 h-[650px] flex flex-col overflow-auto&quot;]/div[@class=&quot;flex-grow&quot;]/div[1]/form[1]/div[@class=&quot;flex flex-col gap-y-4&quot;]/div[2]/div[@class=&quot;relative w-full flex flex-col gap-1 w-full   h-[75px]  h-auto  text-[16px]&quot;]/input[@class=&quot;w-full px-3 h-[52px] flex items-center  border border-[#DEDEDE] placeholder:text-[#DEDEDE] rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 text-black bg-white&quot;]</value>
      <webElementGuid>92e323ec-25ae-4330-9e66-6e7bcda63cfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>96233b50-56b1-4848-8b0e-6ea0acc442dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div[2]/div/form/div/div[2]/div/input</value>
      <webElementGuid>9bf5d375-a1c4-4dad-a2e7-7d3a012c3085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0fc7c254-b2ce-4307-af01-9f3b94dccf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'Input Password']</value>
      <webElementGuid>ea1b7052-c2b7-43ed-a47d-081b74bdc144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
