<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Email</name>
   <tag></tag>
   <elementGuidId>58949185-7d16-4916-a083-4a37148fe115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Input Company Email Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c14ceac1-03ca-417a-80ca-85da9a41c294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>57f2e03f-6035-47a2-8c04-a3318b6c14ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c9c87ac4-46a3-4195-ae34-7f8ab4d793ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Company Email Address</value>
      <webElementGuid>95df60f8-16ba-4803-a80a-f852cf92ba9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 h-[52px] flex items-center  border border-[#DEDEDE] placeholder:text-[#DEDEDE] rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 text-black bg-white </value>
      <webElementGuid>35cb8f59-3bcc-4b5a-90ce-04788cafee67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>fb53a034-5535-48d9-a084-f4c148934c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;flex justify-end md:justify-end items-center bg-cover bg-center global-bg&quot;]/div[@class=&quot;rounded-lg&quot;]/div[@class=&quot;bg-white p-10 rounded-lg w-[528px] mx-[73px] my-8 h-[650px] flex flex-col overflow-auto&quot;]/div[@class=&quot;flex-grow&quot;]/div[1]/form[1]/div[@class=&quot;flex flex-col gap-y-4&quot;]/div[1]/div[@class=&quot;relative w-full flex flex-col gap-1 w-full h-[75px] h-auto  text-[16px]&quot;]/input[@class=&quot;w-full px-3 h-[52px] flex items-center  border border-[#DEDEDE] placeholder:text-[#DEDEDE] rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 text-black bg-white&quot;]</value>
      <webElementGuid>2c8ae2c0-6835-4849-8941-7c7a74251b0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>860aa39a-4fda-48f7-8e77-0fb1402df507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>b962fa6b-35dc-4c18-82d4-4c7e4d437261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>08202925-10ef-47eb-a745-ded6936307ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'Input Company Email Address']</value>
      <webElementGuid>9113fd85-d97d-4ee3-bc8d-73383a5c5bed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
